### ISSUE TITLE
Unable to use URL as app path

### ISSUE THREAD

**Issue by prakharrr** [appium/ruby_lib_core#106]
https://github.com/appium/ruby_lib_core/blob/634d003bdeeeddfca9422b910c197f0530dc49bb/lib/appium_lib_core/driver.rb#L369

This prevents using a URL for the app, is there any other way to use a remote file path for the application ?

**Comment by KazuCocoa** [comment]
ah... that's my wrong. I should set URL if below case, for example..

```
require 'uri'
@caps[:app] if @caps[:app] =~ URI::regexp
```
