### ISSUE TITLE
Warn vs Convert

### ISSUE THREAD

**Issue by titusfortner** [appium/ruby_lib_core#107]
https://github.com/appium/ruby_lib_core/blob/634d003bdeeeddfca9422b910c197f0530dc49bb/lib/appium_lib_core/common/base/bridge.rb#L125

Ruby idiomatic code has `Hash` keys being instances of `Symbol` in snake case. I believe it should be Appium's job to convert this Ruby code into the format required for the JSON package (`String`s with camel case). This is how Selenium has always done it (though Selenium does have its own issues with capabilities).

Is there a reason you went for throwing a warning here instead?

**Comment by KazuCocoa** [comment]
Right. We can remove it.

I added the method when we were developing W3C format in Appium server side. We already finished the work. So, we can remove it.
Thanks for the notice!
