### ISSUE TITLE
[post MJSONWP] /session/:session_id/timeouts

### ISSUE THREAD

**Issue by drzajwo** [appium/ruby_lib_core#128]
## This is a
* [x] Bug report
* [ ] Question
* [ ] Feature Request

## Summary
Tests started to fail with error:

>   1) CW login only user logs in
     Failure/Error: e = error
     
     Selenium::WebDriver::Error::UnknownError:
       An unknown server-side error occurred while processing the command. Original error: '[object Object]' type is not supported for MJSONWP timeout
     # /Library/Ruby/Gems/2.3.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok'
     # /Library/Ruby/Gems/2.3.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
     # /Library/Ruby/Gems/2.3.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/remote/http/common.rb:84:in `new'
     # /Library/Ruby/Gems/2.3.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/remote/http/common.rb:84:in `create_response'
     # /Library/Ruby/Gems/2.3.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/remote/http/default.rb:104:in `request'
     # /Library/Ruby/Gems/2.3.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/remote/http/common.rb:62:in `call'
     # /Library/Ruby/Gems/2.3.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/remote/bridge.rb:164:in `execute'
     # /Library/Ruby/Gems/2.3.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/remote/oss/bridge.rb:584:in `execute'
     # /Library/Ruby/Gems/2.3.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/remote/oss/bridge.rb:66:in `timeout'
     # /Library/Ruby/Gems/2.3.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/common/timeouts.rb:49:in `page_load='

## Environment
* `ruby_lib_core` version: 1.9.0
* Mobile platform/version/device under test:
1. iOS 10.0.2, real device iphone 6
2. iOS 12b7, real device iphone 7s

## Actual behaviour and steps to reproduce
Cannot set timeout, 
```
Selenium::WebDriver::Error::UnknownError:
       An unknown server-side error occurred while processing the command. Original error: [object Object] type is not supported for MJSONWP timeout
```
error occurs.
I belive that it is appium issue because while tracking where the error is called, i get to the point where we are calling post command to appium and gets http 500 error code.

Try to set browser timeout:
i.e. `page.driver.browser.manage.timeouts.page_load = 600`
which calls `:set_timeout` command in `ruby_lib_core/lib/appium_lib_core/common/base/bridge/mjsonwp.rb`
which calls `execute` in `/selenium-webdriver-3.14.0/lib/selenium/webdriver/remote/bridge.rb`
which calls `call` in `gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/remote/http/common.rb`
which eventually calls `request` in `gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/remote/http/default.rb`

where parameters for request are:

> verb: :post
> url: http://localhost:4444/wd/hub/session/good_session_id/timeouts
> headers: {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=UTF-8", "User-Agent"=>"selenium/3.14.0 (ruby macosx)"}
> payload: {:type=>"page load", :ms=>600000}

Response for this request:
`#<Net::HTTPInternalServerError 500 Internal Server Error readbody=true>`

## Expected behaviour
It should set timeout properly. I'm using MJSONWP (force to use it) due to issues with W3C (there was an issue for this problem - 
`Selenium::WebDriver::Error::InvalidArgumentError: Parameters were incorrect. We wanted "W3C protocol expects any of script, pageLoad or implicit to be set" and you sent {"type":"page load","ms":600000}
from BadParametersError: Parameters were incorrect. We wanted "W3C protocol expects any of script, pageLoad or implicit to be set" and you sent {"type":"page load","ms":600000}`)

## Link to Appium/Ruby logs
[Appium logs gist](https://gist.github.com/drzajwo/df697d606a087b2c4f647f1b2836e1f0)

## Any additional comments
Is there any known workaround for this?

**Comment by KazuCocoa** [comment]
`{:type=>"page load", :ms=>600000}` is MJSONWP. It looks server side issue.

Which Appium server did you use?

I guess, it's probably same as https://github.com/appium/appium/issues/11192

**Comment by KazuCocoa** [comment]
Oh, `v1.8.2-beta` is in the gist. thanks.
When did you install the beta? (What about re-install the latest one?)

**Comment by KazuCocoa** [comment]
`selenium-webdriver` calls below. we should make sure the selenium-webdriver's behaviour and fix it if it's wrong.

- oss
```
          def timeout(type, milliseconds)
            execute :set_timeout, {}, {type: type, ms: milliseconds}
          end
```
```
[HTTP] --> POST /wd/hub/session/227b5f59-123d-4dff-8b07-6cea69d248a9/timeouts
[HTTP] {"type":"page load","ms":30000}
[debug] [MJSONWP] Calling AppiumDriver.timeouts() with args: ["page load",30000,null,null,null,"227b5f59-123d-4dff-8b07-6cea69d248a9"]
[debug] [BaseDriver] MJSONWP timeout arguments: {"type":"page load","ms":30000}}
[MJSONWP] Encountered internal error running command: NotImplementedError: Not implemented yet for pageLoad.
[MJSONWP]     at AndroidUiautomator2Driver.callee$0$0$ (/Users/kazuaki/GitHub/appium/node_modules/appium-base-driver/lib/basedriver/commands/timeout.js:89:9)
[MJSONWP]     at tryCatch (/Users/kazuaki/GitHub/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/kazuaki/GitHub/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
```

- w3c
```
          def timeout(type, milliseconds)
            type = 'pageLoad' if type == 'page load'
            execute :set_timeout, {}, {type => milliseconds}
          end
```

(NotImplementedError though)

```
[HTTP] <-- POST /wd/hub/session/4d408cfb-48c6-4088-ad68-727d9c533a1e/timeouts 200 3 ms - 14
[HTTP]
[HTTP] --> POST /wd/hub/session/4d408cfb-48c6-4088-ad68-727d9c533a1e/timeouts
[HTTP] {"pageLoad":30000}
[debug] [W3C] Calling AppiumDriver.timeouts() with args: [null,null,null,30000,null,"4d408cfb-48c6-4088-ad68-727d9c533a1e"]
[debug] [BaseDriver] W3C timeout argument: {"pageLoad":30000}}
[W3C] Encountered internal error running command: NotImplementedError: Not implemented yet for pageLoad.
[W3C]     at AndroidUiautomator2Driver.callee$0$0$ (/Users/kazuaki/GitHub/appium/node_modules/appium-base-driver/lib/basedriver/commands/timeout.js:84:9)
[W3C]     at tryCatch (/Users/kazuaki/GitHub/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/kazuaki/GitHub/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
```

**Comment by drzajwo** [comment]
Hi, 
Thank you for investigating this issue ;) yes, i'm using appium 1.8.2-beta which was reinstalled yesterday, since W3C issues we forced MJSONWP, and everything was good. My previous appium beta build was installed max one week ago, i was testing test environment on different versions of appium and xcode, then after reinstalling to newer build the error started to occur. On monday (utc +1) i'll check again on reinstalled.
Thanks,
Iwo

**Comment by KazuCocoa** [comment]
Thanks! But I appologise you...
I confirmed `package.json` we can get with `npm install -g appium@beta`. I noticed the `appium-base-driver` is `"^2.20.2"`.... the latest base driver is `3.5.1`. So, we must release new beta...

```
114   "dependencies": {↲
115     "appium-android-driver": "3.x",↲
116     "appium-base-driver": "^2.20.2",↲
117     "appium-espresso-driver": "^1.0.0-beta.3",↲
118     "appium-fake-driver": "^0.x",↲
119     "appium-ios-driver": "2.x",↲
120     "appium-mac-driver": "1.x",↲
121     "appium-selendroid-driver": "1.x",↲
122     "appium-support": "2.x",↲
123     "appium-uiautomator2-driver": "1.x",↲
124     "appium-windows-driver": "1.x",↲
125     "appium-xcuitest-driver": "2.x",↲
126     "appium-youiengine-driver": "^1.0.17",↲
127     "argparse": "^1.0.10",↲
128     "async-lock": "^1.0.0",↲
129     "asyncbox": "2.x",↲
130     "babel-runtime": "=5.8.24",↲
131     "bluebird": "3.x",↲
132     "continuation-local-storage": "3.x",↲
133     "dateformat": "^3.0.3",↲
134     "find-root": "^1.1.0",↲
135     "fsevents": "1.x",↲
136     "heapdump": "0.x",↲
137     "lodash": "4.x",↲
138     "npmlog": "4.x",↲
139     "request": "^2.81.0",↲
140     "request-promise": "4.x",↲
141     "semver": "^5.5.0",↲
142     "source-map-support": "0.x",↲
143     "teen_process": "1.x",↲
144     "winston": "2.x"↲
145   },↲
```

The error should be fixed in current master like below with `automationName: 'XCUITest'`.

- W3C

```
_capability","newCommandTimeout":120,"wdaLocalPort":8100,"udid":"2D9E4751-2894-4440-A9A1-96A0B8D68892"}}
[HTTP] <-- POST /wd/hub/session 200 22957 ms - 614
[HTTP]
[HTTP] --> POST /wd/hub/session/3e4310d6-7da9-4fac-92b1-9b5ed3153c8e/timeouts
[HTTP] {"implicit":30000}
[debug] [W3C] Calling AppiumDriver.timeouts() with args: [null,null,null,null,30000,"3e4310d6-7da9-4fac-92b1-9b5ed3153c8e"]
[debug] [XCUITest] Executing command 'timeouts'
[debug] [BaseDriver] W3C timeout argument: {"implicit":30000}}
[debug] [BaseDriver] Set implicit wait to 30000ms
[debug] [W3C] Responding to client with driver.timeouts() result: null
[HTTP] <-- POST /wd/hub/session/3e4310d6-7da9-4fac-92b1-9b5ed3153c8e/timeouts 200 21 ms - 14
[HTTP]
[HTTP] --> POST /wd/hub/session/3e4310d6-7da9-4fac-92b1-9b5ed3153c8e/timeouts
[HTTP] {"pageLoad":30000}
[debug] [W3C] Calling AppiumDriver.timeouts() with args: [null,null,null,30000,null,"3e4310d6-7da9-4fac-92b1-9b5ed3153c8e"]
[debug] [XCUITest] Executing command 'timeouts'
[debug] [BaseDriver] W3C timeout argument: {"pageLoad":30000}}
[debug] [iOS] Set page load timeout to 30000ms
[debug] [W3C] Responding to client with driver.timeouts() result: null
[HTTP] <-- POST /wd/hub/session/3e4310d6-7da9-4fac-92b1-9b5ed3153c8e/timeouts 200 4 ms - 14
[HTTP]
```

- OSS

```
[HTTP] --> POST /wd/hub/session/51abb63b-bfdc-4583-958d-c9bb5e60b3e1/timeouts/implicit_wait
[HTTP] {"ms":30000}
[debug] [MJSONWP] Calling AppiumDriver.implicitWait() with args: [30000,"51abb63b-bfdc-4583-958d-c9bb5e60b3e1"]
[debug] [XCUITest] Executing command 'implicitWait'
[debug] [BaseDriver] Set implicit wait to 30000ms
[debug] [MJSONWP] Responding to client with driver.implicitWait() result: null
[HTTP] <-- POST /wd/hub/session/51abb63b-bfdc-4583-958d-c9bb5e60b3e1/timeouts/implicit_wait 200 5 ms - 76
[HTTP]
[HTTP] --> POST /wd/hub/session/51abb63b-bfdc-4583-958d-c9bb5e60b3e1/timeouts
[HTTP] {"type":"page load","ms":30000}
[debug] [MJSONWP] Calling AppiumDriver.timeouts() with args: ["page load",30000,null,null,null,"51abb63b-bfdc-4583-958d-c9bb5e60b3e1"]
[debug] [XCUITest] Executing command 'timeouts'
[debug] [BaseDriver] MJSONWP timeout arguments: {"type":"page load","ms":30000}}
[debug] [iOS] Set page load timeout to 30000ms
[debug] [MJSONWP] Responding to client with driver.timeouts() result: null
[HTTP] <-- POST /wd/hub/session/51abb63b-bfdc-4583-958d-c9bb5e60b3e1/timeouts 200 4 ms - 76
[HTTP]
```

**Comment by KazuCocoa** [comment]
1.9.0-beta.1 has been released. Please try out it next time.

**Comment by KazuCocoa** [comment]
1.9.0 has been released.
https://github.com/appium/appium/releases/tag/v1.9.0

So, the above should be fixed. If you have issues even updating to 1.9.0, feel free to re-open or create another issue 👍 
@drzajwo

**Comment by drzajwo** [comment]
Thanks @KazuCocoa, on beta everything started to work fine. I'll run test suites on new release.
