### ISSUE TITLE
investigate why CapabilityNotPresentOnTheGridException is raised

### ISSUE THREAD

**Issue by KazuCocoa** [appium/ruby_lib_core#139]
## This is a
* [x] Bug report
* [ ] Question
* [ ] Feature Request

## Summary

Grid environment in https://github.com/appium/ruby_lib/tree/master/grid returns `org.openqa.grid.common.exception.CapabilityNotPresentOnTheGridException: cannot find : Capabilities {app: /Users/kazuaki/GitHub/ruby_..., automationName: XCUITest, deviceName: iPhone Simulator, platformName: ios, platformVersion: 10.3}` if we run grid 3.9+. It also happens with `forceMjsonwp: true`.

With 3.8.1, grid works fine.

https://github.com/appium/ruby_lib_core/pull/138#issuecomment-416770719

## Environment
* `ruby_lib_core` version:
* Mobile platform/version/device under test:

## Link to Appium/Ruby logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.

**Comment by mykola-mokhnach** [comment]
These links might be useful for the investigation:

https://github.com/SeleniumHQ/selenium/blob/07a18746ff756e90fd79ef253a328bd7dfa9e6dc/java/server/src/org/openqa/grid/internal/BaseRemoteProxy.java#L142

https://github.com/SeleniumHQ/selenium/blob/07a18746ff756e90fd79ef253a328bd7dfa9e6dc/java/server/src/org/openqa/grid/internal/TestSlot.java

**Comment by KazuCocoa** [comment]
simply, I needed to update https://github.com/appium/ruby_lib/blob/master/grid/config.json#L7 to `ios` and versions.
It worked with the latest selenium versions and this master.
