### ISSUE TITLE
element.rect - Not performing as expected

### ISSUE THREAD

**Issue by luke-hill** [appium/ruby_lib_core#285]
## This is a
* [x] Bug report
* [ ] Question
* [ ] Feature Request

## Summary
See linked issue here for full details. Essentially the response from `element.rect` doesn't play nicely with sticky/freeze panes.

https://github.com/SeleniumHQ/selenium/issues/8869

Sample responses good/bad

A few more updated test candidates - All ran through browserstack - Note the y co-ordinate playing up. Maybe this is something specific to a certain area. Maybe this is specific to appium or iOS not sure.

**Bad candidates**
```
iPhone 8 - iOS 12 - #<struct Selenium::WebDriver::Rectangle x=17, **y=1**, width=293, height=48>
iPhone 8 - iOS 13 - #<struct Selenium::WebDriver::Rectangle x=17, **y=1**, width=293, height=48>
iPhone 11 - iOS 13 - #<struct Selenium::WebDriver::Rectangle x=17, **y=1**, width=332, height=48>
```
**Good candidates**
```
Windows 7 - Chrome v83 - #<struct Selenium::WebDriver::Rectangle x=17, y=**1032**, width=750, height=48>
Windows 10 - Chrome v86 - #<struct Selenium::WebDriver::Rectangle x=17, y=**1060**, width=750, height=48>
Windows 10 - Firefox v80 - #<struct Selenium::WebDriver::Rectangle x=17.0, y=**1010.0**, width=750.0, height=48.0>
OSX Mojave - Safari 12 - #<struct Selenium::WebDriver::Rectangle x=17, y=**820**, width=750, height=48>

**Comment by luke-hill** [comment]
Ping @KazuCocoa Not sure if this is the right repo sorry. I moved this from the selenium one, but I got lost in which one to place it.

**Comment by KazuCocoa** [comment]
The result depends on iOS, Safari versions, Xcode version and device models, but it is hard to say what combination could be wrong since they are blackbox. Appium does not modify the result, basically.
Probably, you want to report it to Apple.

**Comment by luke-hill** [comment]
I've tried multiple iOS devices and they all seem broken? Could you maybe advise where to report it. As I've been passed around a bit and I'm losing my train of thought, as this feels quite a fundamental break.

**Comment by KazuCocoa** [comment]
I haven't reported like this issue, but Apple or WebKit is proper as you did.
Btw, you also can try out https://webkit.org/blog/9395/webdriver-is-coming-to-safari-in-ios-13/

Appium communicates with WebView via Safari WebInspector. So, the value could be different from safaridriver as the above, but if safaridriver also depends on their internal WebInspector stuff, the result might be the same.
https://github.com/appium/appium-safari-driver will be in the next release (not 1.19.0 current RC) to use safaridriver.

---

Android depends on chromedriver and Chrome versions. The result could be different from iOS's one.
