### ISSUE TITLE
Error on @core.appium_server_version

### ISSUE THREAD

**Issue by Echenique** [appium/ruby_lib_core#310]
## This is a
* [X] Bug report
* [ ] Question
* [ ] Feature Request

## Summary
When I running my script with remote appium server, after connection with device script broken oaths point:
/Library/Ruby/Gems/2.6.0/gems/appium_lib-10.6.0/lib/appium_lib/driver.rb:384:in `rescue in appium_server_version'

idk why, but I comment this line (driver.rb:384) and script run completely.

## Environment
* `ruby_lib` version: 10.6.0 

## Link to Appium/Ruby logs
https://gist.github.com/Echenique/c9394eb0042dcf2b6b0e3d5b1c74a611

**Comment by KazuCocoa** [comment]
The API calls `/wd/hub/status` to get the server version. https://www.w3.org/TR/webdriver1/#dfn-status
Thus, the root issue was `http://<MY_EXTERNAL_SERVER>/api/mobile/wd/hub` returns 404.

In general, Appium server returns like `{"value":  {"build":{"version":"1.21.0-beta.0","git-sha":"5735c828f1ce00e99243368bd5a60acc70809dcd","built":"2021-02-11 23:32:55 -0800"}}}` response.

**Comment by KazuCocoa** [comment]
https://github.com/appium/ruby_lib_core/pull/311 will be able to ignore such errors, but potentially some method depends on appium version may behave wrong.
Ideally, `http://<MY_EXTERNAL_SERVER>/api/mobile/wd/hub/status` should return expected Appium server response.

**Comment by Echenique** [comment]
how i can set a timeout to client wait before call a status? i think if client check status with a little delay will work to me..

**Comment by KazuCocoa** [comment]
Sorry, what do you mean?
Do you want to add like `sleep` before this `appium_server_version` call in `start_driver`?
https://github.com/appium/ruby_lib/blob/219181d80f3b86999706f90a68996945fdc7b1d0/lib/appium_lib/driver.rb#L556
`wd/hub/status` should work without any session establishments as an appium server. The call occurs after succeeding the new session request for now.

So far, the library cannot handle the case, `wd/hub/status` works after a while after succeeding the new session request.
(It means probably you want to add `sleep` in `start_driver`.
As a workaround, you can modify your local `/Library/Ruby/Gems/2.6.0/gems/appium_lib-10.6.0/lib/appium_lib/driver.rb` file with adding such `sleep`. (Not good way, but technically can)

**Comment by Echenique** [comment]
works with version 4.4.0 thank you (=
