### ISSUE TITLE
Attaching Appium Clients to Existing Sessions

### ISSUE THREAD

**Issue by tai2** [appium/ruby_lib_core#336]
## This is a
* [ ] Bug report
* [ ] Question
* [x] Feature Request

## Summary

We want to reuse an existing session without initializing another driver using a session id like [this](
https://appiumpro.com/editions/78-attaching-appium-clients-to-existing-sessions).
As long as I know ruby_lib_core doesn't support this usage.

Currently, we're achieving this with a monkey patch but we ideally want to do this without the dirty hack.

Do you think it's possible to support this feature officially?

I've found one difficulty so far.  The official selenium-webdriver library permits the `new_session` command initially.
We cannot send the `status` command before sending a `new_session` command.
As a result, we cannot retrieve the capabilities of an existing session.

We perhaps have to tweak the selenium-webdriver client beforehand.

The patch we're using is this.

```
module Appium
  module Core
    class Base
      class Bridge
        def self.resume_session(session_id, dialect, capabilities, **opts)
          case dialect
          when "oss" # for MJSONWP
            Bridge::MJSONWP.new(capabilities, session_id, **opts)
          when "w3c"
            Bridge::W3C.new(capabilities, session_id, **opts)
          else
            raise Appium::Core::Error::CoreError, 'cannot understand dialect'
          end
        end
      end

      module DriverExtension
        def initialize(opts = {})
          if opts[:desired_capabilities][:saved_session]
            desired_capabilities = opts.delete(:desired_capabilities)
            saved_session = desired_capabilities[:saved_session]
            listener = opts.delete(:listener)
            @bridge = ::Appium::Core::Base::Bridge.resume_session(
              saved_session[:id],
              saved_session[:dialect],
              saved_session[:capabilities],
              **opts
            )
            method(__method__).super_method.super_method.call(@bridge, listener: listener)
          else
            super(opts)
          end
        end
      end

      class Driver
        prepend DriverExtension
      end
    end
  end
end
```

## Environment
* `ruby_lib_core` version: 4.7.1
* Mobile platform/version/device under test: iOS

**Comment by KazuCocoa** [comment]
Thank you.
Let me consider it.

Previously, I considered adding the feature, but then, I decided just to follow selenium-webdriver client. (They decided to not support such attach feature according to in their historical issues)

This library includes/excludes modules depending on the app under test.
So, it needs to load modules properly after attaching to a session, and calling `get capabilities` endpoint.

**Comment by KazuCocoa** [comment]
I implemented this partially in https://github.com/appium/ruby_lib_core/pull/337

It still needs to tweak.
The basic idea is:

1. Call `GET /session/<session_id>`
2. Check the response if the version is oss/w3c and its platform
3. Adjust methods for the platform/automation name

W3C WebDriver spec does not define `GET /session/<session_id>` endpoint. Potentially Appium will also remove the endpoint or change the endpoint only for Appium usage in the future.
Then, step 3 will be necessary to be set explicitly before attaching to an existing session for now.
Step 2 will no longer be necessary once this client switches to selenium 4 based one. (since it only supports W3C spec)
