### ISSUE TITLE
Update screen recording commands

### ISSUE THREAD

**Issue by KazuCocoa** [appium/ruby_lib_core#48]
## This is a
* [ ] Bug report
* [ ] Question
* [x] Feature Request

## Summary

- Change the parameter of screen recording
    - https://github.com/appium/appium-base-driver/pull/168

## Environment
* `ruby_lib_core` version:
* Mobile platform/version/device under test:

## Link to Appium/Ruby logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-android-driver/pull/310

**Comment by mykola-mokhnach** [comment]
Linking  https://github.com/appium/appium-xcuitest-driver/pull/609
