### ISSUE TITLE
Missing symbol set in set_automation_name_if_nil method

### ISSUE THREAD

**Issue by drzajwo** [appium/ruby_lib_core#50]
## This is a
* [x] Bug report
* [ ] Question
* [ ] Feature Request

## Summary
I'd like to call a bug in ruby_lib_core/lib/appium_lib_core/driver.rb.
The problem i'm having is with setting `:automationName` parameter. I'm running appium with bash script, that set all caps, including automationName as a string `"automationName": "xcuitest"`.
While calling appium caps not displays `:automationName` param and method `automation_name_is_xcuitest?` is returning `false`.
Now I have to make env var `automation_name=xcuitest` and hardcoded 
`caps = caps.merge({automationName: ENV['automation_name']}) unless ENV['automation_name'].nil?`

## Environment
* `ruby_lib_core` version: 
* Mobile platform/version/device under test: Real device, iPhone 7 (9, 3), iOS 11.1.1; Appium 1.7.1

## Actual behaviour and steps to reproduce
That's appium_lib_core/driver.rb methods with problem:

      def set_automation_name
        @automation_name = @caps[:automationName] if @caps[:automationName]
        @automation_name = if @automation_name
                             @automation_name.is_a?(Symbol) ? @automation_name : @automation_name.downcase.strip.intern
                           end
      end

      def set_automation_name_if_nil
        return unless @automation_name.nil?
        @automation_name = @driver.capabilities['automationName']
      end

In method set_automation_name_if_nil as You can see var isn't set as a symbol by calling `intern` option like it is in above method `set_automation_name`.
## Expected behaviour
The method `set_automation_name_if_nil` should set `@automation_name` as a symbol by calling `intern` option.

## Link to Appium/Ruby logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.

**Comment by KazuCocoa** [comment]
Thanks!

I've created a PR => https://github.com/appium/ruby_lib_core/pull/52
And could you apply the branch to your environment if you have a time?

Anyway, I'll merge this tomorrow.

**Comment by KazuCocoa** [comment]
@drzajwo ^

**Comment by drzajwo** [comment]
@KazuCocoa Thanks! I'll try it on monday ;)

**Comment by KazuCocoa** [comment]
Please try 1.2.6
https://github.com/appium/ruby_lib_core/blob/master/CHANGELOG.md#126---2018-01-21

**Comment by drzajwo** [comment]
It's working fine, but to be clear it's still missing 'downcase.strip' befor intern call. 
It just make all letters downcase and removes spaces but I thing it should be there as well.
Thank you at all for those changes.

**Comment by KazuCocoa** [comment]
🆗 
Thanks! I'll work soon.

https://github.com/appium/ruby_lib_core/pull/52/files

- 📝 for me
    - insert `.downcase.strip`

**Comment by KazuCocoa** [comment]
https://github.com/appium/ruby_lib_core/commit/803cbbb42ccd1cb193d90aa48d4240ada520633f

**Comment by KazuCocoa** [comment]
https://github.com/appium/ruby_lib_core/blob/master/CHANGELOG.md#127---2018-01-25-1
