### ISSUE TITLE
Issue introduced after drop support of snake to camel case conversion

### ISSUE THREAD

**Issue by eirenik0** [appium/ruby_lib_core#569]
## This is a
* [x] Bug report
* [ ] Question
* [ ] Feature Request

## Summary

A bug in capability handling causes `platformName` to be incorrectly set as "MAC" for iOS devices, despite being originally set to "iOS". This issue stems from inconsistent conversion of capability keys in Core.Bridge, where `platformName` and `browserName` are converted to `platform_name` and `browser_name`, respectively, while other capabilities remain unchanged.

## Environment
* `ruby_lib_core` version: 9.0.0 and above (I use `appium_lib 15.1.0`)
* Mobile platform/version/device under test: iOS 16.0, iPhone 8 Simulator ( would work any )

## Actual behaviour and steps to reproduce

1. Set up capabilities for an iOS device test:

```ruby
caps = {
  "browserName": '',
  "platformName": 'iOS',
  "appium:platformVersion": '16.0',
  "appium:newCommandTimeout": 600,
  "appium:app": 'storage:filename=awesomeswift_classic.app.zip',
  "appium:deviceName": 'iPhone 8 Simulator',
  "appium:automationName": 'XCUITest',
  "appium:orientation": 'PORTRAIT',
}
```

2. Initialize the Appium driver:

```ruby
driver = Appium::Driver.new({caps: caps}, true)
driver.start_driver
```

3. Inspect the session capabilities:
<img width="777" alt="Screenshot 2024-08-01 at 00 15 59" src="https://github.com/user-attachments/assets/3d68534a-db9d-4578-990a-d3e8996c0553">

4. Observe that:
   a. `platformName` has been changed to `platform_name` internally.
   b. When we fetch info about driver from external client the `platformName` becomes "MAC" instead of the original "iOS".

5. This incorrect platformName propagates to dependent SDKs (e.g., Applitools USDK), causing issues with screenshot calculations and potentially other platform-specific behaviors.

## Expected behaviour

1. The keys `platformName` and `browserName` should remain in their original camelCase form, consistent with other capabilities.
2. The value of `platformName` should remain "iOS" as originally set in the capabilities, without being overwritten by an incorrect "MAC" value.

## Link to Appium/Ruby logs

In appium logs there is no snake case values, only proper one

**Comment by KazuCocoa** [comment]
After some checking, I wondered https://github.com/appium/ruby_lib/blob/0d1c2b87b8f2ac456372bf4cbb2441fffae5cf27/lib/appium_lib/driver.rb#L208-L243 or around was broken since the version.

So, in your case, `@core.device` and `@core.automation_name` values in the ruby_lib. Then, it is actually breaks the ruby_lib in case you gave `appium:` capabilities.

Then, perhaps these capabilities would fix the issue.
```
caps = {
  :browserName: '',
  :platformName: :ios,
  :automationName: :xcuitest,
  "appium:platformVersion": '16.0',
  "appium:newCommandTimeout": 600,
  "appium:app": 'storage:filename=awesomeswift_classic.app.zip',
  "appium:deviceName": 'iPhone 8 Simulator',
  "appium:orientation": 'PORTRAIT',
}
```
(for this case, I'll fix this lirbary to return symbol properly for the ruby_lib quickly)

Or do you reference the vanilla `driver.capabilities`?

**Comment by eirenik0** [comment]
@KazuCocoa thanks for fixing this issue!
